### ISSUE TITLE
Fail to reproduce tutorial sample results in 2014 paper

### ISSUE THREAD

**Issue by gengyuncong** [aroth85/pyclone#7]
Hi,

I analyze the tutorial data provided using the latest PyClone version. However, I ended up with 9 clusters which is different from results of the nature paper published in 2014. 
I have some questions:
1. Are the tutorial data (SRR385938-SRR385941) same as the one used in nature paper? 
2. Do I need to tune any parameters in order to reproduce the result?
3. Is there any inconsistency due to version update? 
Thank you!

Here is what I got:
[test.pdf](https://github.com/aroth85/pyclone/files/3092168/test.pdf)

Here is my config file:
```
num_iters: 10000

base_measure_params:
 alpha: 1
 beta: 1

concentration:
 value: 1.0

 prior:
   shape: 1.0
   rate: 0.001

density: pyclone_beta_binomial

beta_binomial_precision_params:
 value: 1000

 prior:
   shape: 1.0
   rate: 0.0001

 proposal:
   precision: 0.01

working_dir: /Users/apple/FCBB-final/data/tutorial

trace_dir: trace

samples:
 SRR385938:
   mutations_file: yaml/SRR385938.yaml

   tumour_content:
     value: 1.0

   error_rate: 0.001

 SRR385939:
   mutations_file: yaml/SRR385939.yaml

   tumour_content:
     value: 1.0

   error_rate: 0.001

 SRR385940:
   mutations_file: yaml/SRR385940.yaml

   tumour_content:
     value: 1.0

   error_rate: 0.001

 SRR385941:
   mutations_file: yaml/SRR385941.yaml

   tumour_content:
     value: 1.0

   error_rate: 0.001
```
